apiVersion: v1
kind: Pod
metadata:
  name: data-downloader-pod
  namespace: equitian-app
spec:
  imagePullSecrets:
    - name: regcred
  containers:
  - name: data-downloader-container
    image: docker.pkg.github.com/source-nerd/yahoo-data-downloader-docker-elastic/yahoo-data-downloader-docker-elastic:0.1
    env:
    - name: ES_HOST
      value: ES_HOST
    - name: ES_PORT
      value: "9200"
    - name: ES_USERNAME
      value: "elastic"
    - name: ES_PASSWORD
      value: ES_PASSWORD
    - name: INDEX_1_MIN
      value: INDEX_1_MIN
    - name: INDEX_1_DAY
      value: INDEX_1_DAY
    - name: STOCKS
      value: "AAPL,TSLA,MSFT"
  restartPolicy: OnFailure
